### ISSUE TITLE
Add possibility to provide a custom name for test run, which will be sent to TestRail

### ISSUE THREAD

**Issue by viktorgogulenko** [Slobo989/jasmine-2-testrail#5]
It would be great to have a chance to provide custom name for test run instead of current "May 15, 2019, 13:52:29" so we could specify in that way that "this specific test run was created from automated test run and not by someone else".

**Comment by zeljkosimic95** [comment]
We've added the ability to name a new TestRun with a new parameter 'runName'.
```javascript
protractor conf --params.runName=TestRun1
```
If not specified, the run will be named after the current date and time.
Feature: #6

**Comment by viktorgogulenko** [comment]
Sorry, guys - I've tried 

>  params: {
>   runName: true,
> },

with `--params.runName=AutomatedTestRun`
and it always sending a testrun with name like:
`Created new test run: 20 May 2019, 15:25:05`

Could I miss something from my side?

**Comment by zeljkosimic95** [comment]
If the runName is false (or undefined), the run name will default to the current date and time. But, if you change the runName parameter to a string (for example 'TestRun1'), it should be called by that name. And if you want to define it from the command line, leave it as false in the params, and add --params.runName=TestRun1 to the command line.
So the runName parameter is not the check whether you want to name the run or not, but the actual name of the run (except when set to false, then it's the date).
Sorry if we made that a bit convoluted, maybe setting the initial runName parameter to undefined would solve the confusion (because undefined also counts as false in the if statements we use).

**Comment by viktorgogulenko** [comment]
Thanks for the quick answer!
I've tried such config as well:
`params: {
        runName: 'AutomatedTestRun'
        }`

without providing of command line parameter and it also creating a test run just with date:

> [16:10:33] I/launcher - chrome #01 passed
> Created new test run: 20 May 2019, 16:10:33
> Added test results

**Comment by zeljkosimic95** [comment]
You also need to add browser.params.runName to the createRun method in the afterLaunch section, like this :
```javascript
reporter.createRun(1, 1, browser.params.runName)
```
I forgot to mention it here after updating the readme, sorry!
